# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: +0800

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: LyTopia # the main title

tagline: "<b>THINK!</b> THINK WILDLY!!"

tips:
  - "<b>Tip 0x00:</b><br>Redemption lies within."
  - "<b>Tip 0x01:</b><br>&quot;If you want to win, prioritize learning over winning.&quot;"
  - "<b>Tip 0x02:</b><br>Be a Life-Combo Breaker."
  - "<b>Tip 0x03:</b><br>Contemplate the moments that are beyond your control."
  - "<b>Tip 0x04:</b><br>Tired of being brave? A shot of insanity should help!"
  - "<b>Tip 0x05:</b><br>With great power comes... huge electricity bill."
  - "<b>Tip 0x06:</b><br>The world only makes sense if you force it to. — Batman."
  - "<b>Tip 0x07:</b><br>You’re choosing how to use your time. Do you realize that?"
  - "<b>Tip 0x08:</b><br>&quot;Don’t turn your head. You will lose your balance.&quot;"
  - "<b>Tip 0x09:</b><br>Knock, knock! Wait... I'm the host..."
  - "<b>Tip 0x0a:</b><br>Welcome to LyTopia, traveler!"
  - "<b>Tip 0x0b:</b><br>&quot;There is no Sanity Clause!&quot;"
  - "<b>Tip 0x0c:</b><br>莫笑痴"
  - "<b>Tip 0x0d:</b><br>&quot;与其绝望死去，不如纵情燃烧&quot;"
  - "<b>Tip 0x0e:</b><br>&quot;我身我心，我枪而已&quot;"
  - "<b>Tip 0x0f:</b><br>活着的人总都有点执念，谁也不能笑谁"
  - "<b>Tip 0x10:</b><br>&quot;能形式化就能自动化&quot;"
  - "<b>Tip 0x11:</b><br>The true self = The perceiving subject"
  - "<b>Tip 0x12:</b><br>&quot;You have to keep pretending that life makes sense, that there’s some point to all this struggling!&quot;"
  - "<b>Tip 0x13:</b><br>&quot;Drinking beer every day is healthier for you than being dead.&quot;"
  - "<b>Tip 0x14:</b><br>&quot;Whatever doesn't kill you simply makes you stranger&quot;"
  - "<b>Voice-Over 0x00:</b><br>(A soft, continuous buzzing hums in the background, barely perceptible.)"
  - "<b>Voice-Over 0x01:</b><br>(A human being is reading this text.)"
  - "<b>Riddle 0x00:</b><br>&quot;What good amid these, O me, O life?&quot;"
  - "<b>Riddle 0x01:</b><br>I come in darkness, but fill the mind with light. What am I?"
  - "<b>Riddle 0x02:</b><br>I am a journey that everyone will take, certain yet unknown. What am I?"

description: >- # used by seo meta and the atom feed
  Yue Lin's personal website.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://yuelin301.github.io"

github:
  username: YueLin301 # change to your github username

# twitter:
  # username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Yue Lin
  email: linyue3h1@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username # change to your twitter homepage
    - https://github.com/YueLin301 # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: d2Lg5eCqHini4wHtZ-c84NNCK97UHcbAhQzVJHekMZQ # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-FP0Z4ZT4ZK # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

mouse_click_effect: true

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: assets/img/avatar/meow5.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: false # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
